# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govital < Formula
  desc "Go dependency maintenance scanner"
  homepage "https://github.com/steffakasid/govital"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/govital/releases/download/v1.0.0/govital_1.0.0_darwin_amd64.tar.gz"
      sha256 "e7027c3f4ede31ed10c746dfa6b3ef067967aa46d729c1755fe8a382517cfe9c"

      def install
        bin.install "govital"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/govital/releases/download/v1.0.0/govital_1.0.0_darwin_arm64.tar.gz"
      sha256 "59497956d97816acc94b680d6c810c1b0ebbe8c574c9d316c5a61527bf936ec9"

      def install
        bin.install "govital"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/govital/releases/download/v1.0.0/govital_1.0.0_linux_amd64.tar.gz"
        sha256 "3a26a45dc08759304ca134e42ac30e5de82944af4ca85d725b3f8f6c78e25507"

        def install
          bin.install "govital"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/govital/releases/download/v1.0.0/govital_1.0.0_linux_arm64.tar.gz"
        sha256 "dc75e4cef893e85a57ef1e42b607a064b52831b791daedbb8d9650e3e7aa8b3a"

        def install
          bin.install "govital"
        end
      end
    end
  end
end
