# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govital < Formula
  desc "Go dependency maintenance scanner"
  homepage "https://github.com/steffakasid/govital"
  version "0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/govital/releases/download/0.4/govital_0.4_darwin_amd64.tar.gz"
      sha256 "b17a56c8d125c3653ce9de437ab02e6bb99f5cb41e2f59052863f0b1c14ed3b6"

      def install
        bin.install "govital"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/govital/releases/download/0.4/govital_0.4_darwin_arm64.tar.gz"
      sha256 "8e28a75c3067d6aa60a127f9d37f63c125e88b13d3c36d582235fe8d1066b9a7"

      def install
        bin.install "govital"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/govital/releases/download/0.4/govital_0.4_linux_amd64.tar.gz"
      sha256 "7dc81c1a068332292a52d7331c0355743e4a582f0cca48eab52c25ab2bf99291"
      def install
        bin.install "govital"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/govital/releases/download/0.4/govital_0.4_linux_arm64.tar.gz"
      sha256 "d2d79ae4ecc136ce09003a69f6cb20c6305a29a2463b5868dc878a8107f8a8a1"
      def install
        bin.install "govital"
      end
    end
  end
end
